baseURL               = "https://www.avmode.eu.org/"
languageCode          = "zh-CN"
title                 = "WebStack ç½‘å€å¯¼èˆª"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"					# ç«™ç‚¹é™æ€æ–‡ä»¶ä¿å­˜ç›®å½•


[params]
    author        = "aizhiqian"
    description   = "Webstack-Hugo ç½‘å€å¯¼èˆª | Hugo ä¸»é¢˜"
    upload        = "https://www.yuque.com/forms/share/c6c1592b-ae7e-48b4-97c1-15fb6c67b9f1"  # å·¦ä¾§å¯¼èˆªæ çš„"ç½‘ç«™æäº¤"
    about         = "https://weiyan.cc/discussions-10/"	          # å·¦ä¾§å¯¼èˆªæ çš„"å…³äºå¯¼èˆª"é¡µé¢(./about)
    repository    = "https://github.com/shenweiyan/WebStack-Hugo"
    enablePreLoad = true					# ç½‘ç«™å®Œå…¨æ‰“å¼€å‰é¢„åŠ è½½åŠ¨ç”»
    textPreLoad   = "å‘æ—¥è‘µğŸŒ»å¯¼èˆª"				# é¢„åŠ è½½çš„åŠ¨ç”»æ–‡å­—, åªæœ‰å½“enablePreLoad=trueæ—¶ç”Ÿæ•ˆ
    expandSidebar = true					# é»˜è®¤å±•å¼€å·¦ä¾§è¾¹å¯¼èˆªæ 
    logosPath     = "assets/images/logos"			# ç½‘ç«™æ¯ä¸ªå¯¼èˆªåœ°å€logoå­˜æ”¾åœ°å€
    defaultLogo   = "assets/images/logos/default.webp"		# logoå›¾ç‰‡èµ„æºä¸å­˜åœ¨æˆ–è€…é”™è¯¯æ—¶, é»˜è®¤æ˜¾ç¤ºçš„logo; è¯¥å‚æ•°å¦‚ä¸ºç©º,å°†ä¼šä¸€ç›´åŠ è½½å¯¹åº”çš„logo,ç›´è‡³æˆåŠŸ
    nightMode     = false					# é»˜è®¤ç«™ç‚¹ä¸ºæ·±è‰²(å¤œé—´)æ¨¡å¼
    yiyan         = true                         		# é»˜è®¤å¯ç”¨ä¸€è¨€æœåŠ¡

[params.seo]
    baiduhmid       = ''	# ç™¾åº¦ç»Ÿè®¡ hm.src çš„ ID
    baiduSiteVer    = ''	# ç™¾åº¦HTMLæ ‡ç­¾éªŒè¯(baidu-site-verification)
    tj51laid        = ''    # 51.LA ç½‘ç«™ç»Ÿè®¡
    tj51lack        = ''
    GoogleAdsClient = ''	# Google AdSense

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/bg-dna.jpg"		# æœç´¢éƒ¨åˆ†æµ…è‰²èƒŒæ™¯å›¾
    searchImageD      = "assets/images/bg-dna.jpg"		# æœç´¢éƒ¨åˆ†æ·±è‰²èƒŒæ™¯å›¾
    logoExpandLight   = "assets/images/bt8-expand-light.png"
    logoExpandDark    = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "assets/images/bt.png"
    logoCollapseDark  = "assets/images/bt.png"

[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = 'æœ¬ç«™å†…å®¹æºè‡ªäº’è”ç½‘ï¼Œå¦‚æœ‰å†…å®¹ä¾µçŠ¯äº†ä½ çš„æƒç›Šï¼Œè¯·è”ç³»åˆ é™¤ç›¸å…³å†…å®¹ <br/>&copy; 2024 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | [çŸ¥å¿ƒ](https://www.aizhiqian.eu.org/)<br/>'
